### ISSUE TITLE
Request: change defName of designation cat Storage to specify mod

### ISSUE THREAD

**Issue by lilwhitemouse** [cheetah/QuantumStorageRedux#3]
Your DesignationCategoryDef has a defName of Storage. I have been getting reports for several weeks about duplicate "Storage" menus from people using Deep Storage, and I couldn't figure out who had the other mod, because the defName didn't give anything away.

Could you change it to "QSRStorage" or "StorageQSR" or somesuch?

**Comment by cheetah** [comment]
Sure, I'll look into it as soon as I can
